#!/bin/bash 
export PROOT=$(pwd)
SESSION_NAME="$(basename $PROOT)-$(echo $PROOT | md5)"

INIT_TMUX="TRUE"

(tmux ls -F '#S' 2>/dev/null | grep -x $SESSION_NAME) && INIT_TMUX="FALSE"

if [ "$INIT_TMUX" == "TRUE" ]
then
    tmux new-session -d -s $SESSION_NAME -n 'cmd'
    tmux split-window -t $SESSION_NAME -h
    tmux new-window -t $SESSION_NAME -n 'src' -c "$(pwd)/src"
    tmux send-keys -t $SESSION_NAME:src 'vim -c NERDTree' 'C-m' 'O' 
fi
tmux -2 attach-session -t $SESSION_NAME -d
